Repository mohsen-najafizadeh/telegram-notifier, pull requests merged in 2024-12, with the labels that each got.

#2 Initial project setup with core files, documentation, and features
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  DOCUMENTATION.md
  README.md
  composer.json
  composer.lock
  src/Exceptions/TelegramException.php
  src/Telegram.php
  tests/Unit/TelegramTest.php
Labels: documentation, enhancement

#3 Release v1.0.0 - Initial Stable Version
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  DOCUMENTATION.md
  README.md
  composer.json
  composer.lock
  src/Exceptions/TelegramException.php
  src/Telegram.php
  tests/Unit/TelegramTest.php
Labels: documentation, enhancement

#6 Add link to documentation in README
  README.md
Labels: documentation

#7 Merge development branch into main: Add documentation link to README
  README.md
Labels: documentation

#9 Setup Docker Environment for Consistent Development Workflow
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  README.md
  composer.json
  composer.lock
  docker-compose.yml
Labels: documentation, enhancement

#13 Merge v1.1.0 Release Changes into Main
  CHANGELOG.md
  composer.json
  src/Telegram.php
  tests/Unit/TelegramTest.php
Labels: bug
